cod1, qtde1, valor1 = input().split(" ")
qtde1 = int(qtde1)
valor1 = float(valor1)
cod2, qtde2, valor2 = input().split(" ")
qtde2 = int(qtde2)
valor2 = float(valor2)
print("VALOR A PAGAR: R$ {:.2f}".format((qtde1 * valor1) + (qtde2 * valor2)))